name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set up JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: adopt
          java-version: 21
      - name: Build LimboAPI
        run: ./gradlew build
      - name: Upload LimboAPI
        uses: actions/upload-artifact@v3.0.0
        with:
          name: LimboAPI
          path: "*/build/libs/*.jar"
